version: '3.5'

services:
  nginx:
    image: fnandot/nginx:1.11-mpwar
    depends_on:
      - php-fpm
    ports:
      - 8080:80
    volumes:
      - "./mysite.conf:/etc/nginx/conf.d/000_site.conf"
      - "./:/app"
    env_file:
      - docker.env

  php-fpm:
    image: fnandot/php-fpm:7.3-mpwar
    volumes:
      - "./:/app"
  composer:
    image: "composer"
    volumes:
      - "./:/app"
    command: sh -c "composer global require hirak/prestissimo && composer update && composer dump-autoload -o"

